/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Bottle } from "./Bottle";
export * as factories from "./factories";
export { Bottle__factory } from "./factories/Bottle__factory";
